repos:

- repo: https://github.com/pycqa/isort
  rev: 5.6.4
  hooks:
  - id: isort

- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
  - id: black
    language_version: python3.8

- repo: https://github.com/life4/flakehell
  rev: v.0.7.1
  hooks:
  - id: flakehell
