version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:dbpass@pg:5432/db
    command: bash -c "./etc/wait_for_it.sh pg:5432 -s -t 30 -- yoyo apply --database $$DATABASE_URL ./migrations && python ./manage.py init-db && uvicorn asgi:app --host 0.0.0.0 --port 8080"

  pg:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=db
    ports:
      - "5555:5432"
